version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - grafana
      - prometheus
    networks:
      - monitoring

  frontend:
    image: ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/realtime-chat-app/frontend:${APP_VERSION}  #  dynamic
    container_name: frontend
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--web.external-url=http://realtime-chat-app-dev-alb-18324781.us-east-1.elb.amazonaws.com/prometheus/'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://realtime-chat-app-dev-alb-18324781.us-east-1.elb.amazonaws.com/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=realtime-chat-app-dev-alb-18324781.us-east-1.elb.amazonaws.com
    depends_on:
      - prometheus
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
      - monitoring