FROM ubuntu:latest

LABEL name="myImage"

ENV aws_access_key_id=asdasdasd\
    aws_secrest_key_id=adasdasdad\
    aws_default_region=us-east-a1

ARG T_VERSION='1.6.6'\
    P_VERSION='1.6.6'

RUN apt update && apt install -y jq net-tools curl wget\
    && apt install -y nginx iputils-ping unzip

RUN wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip \
    && wget https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip\
    && unzip terraform_${T_VERSION}_linux_amd64.zip  && unzip packer_${P_VERSION}_linux_amd64.zip\
    && chmod 777 terraform && chmod 777 packer\
    && ./terraform version && ./packer version 

CMD ["nginx","-g","daemon off;"]