# events {}

# http {
#   server {
#     listen 80;

#     # Frontend (Node app)
#     location / {
#       proxy_pass http://frontend:3000;
#       proxy_set_header Host $host;
#       proxy_set_header X-Real-IP $remote_addr;
#     }

#     # Grafana
#     location /grafana/ {
#       proxy_pass http://grafana:3000/;
#     }

#     # Prometheus
#     location /prometheus/ {
#       proxy_pass http://prometheus:9090/;
#     }
#   }
# }

events {}

http {
  server {
    listen 80;

    # Frontend
    location / {
      proxy_pass http://frontend:3000;
    }

    # Grafana (IMPORTANT HEADERS)
    location /grafana/ {
      proxy_pass http://grafana:3000/grafana/;

    }

    # Prometheus
    location /prometheus/ {
  proxy_pass http://prometheus:9090/prometheus/;
}
  }
}